---
# Checks for implementations of the hash method which combine values using
# custom logic instead of delegating to Array#hash.
Security/CompoundHash:
  Enabled: true

# This cop checks for the use of JSON class methods which have potential
# security issues.
Security/JSONLoad:
  Enabled: true

# This cop checks for the use of *Kernel#eval*.
Security/Eval:
  Enabled: true

# Checks for the first argument to IO.read, IO.binread, IO.write, IO.binwrite, IO.foreach, and IO.readlines
Security/IoMethods:
  Enabled: true
